---
version: "{build}"

install:
- cmd: git clone --depth 3 https://github.com/loc-rdc/bagit-conformance-suite.git

build_script:
- cmd: ./gradlew.bat check --no-daemon

shallow_clone: true

cache:
  - '%USERPROFILE%\.gradle'

notifications:
- provider: Email
  to:
  - jsca@loc.gov
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
